// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Threes.Registration.Persistence;

#nullable disable

namespace Threes.Registration.Persistence.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20260607171438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Threes.Registration.Domain.Lookups.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Nasr City"
                        },
                        new
                        {
                            Id = 102,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Maadi"
                        },
                        new
                        {
                            Id = 103,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Heliopolis"
                        },
                        new
                        {
                            Id = 104,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Zamalek"
                        },
                        new
                        {
                            Id = 105,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "New Cairo"
                        },
                        new
                        {
                            Id = 201,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Dokki"
                        },
                        new
                        {
                            Id = 202,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Mohandessin"
                        },
                        new
                        {
                            Id = 203,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "6th of October"
                        },
                        new
                        {
                            Id = 204,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Haram"
                        },
                        new
                        {
                            Id = 205,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Sheikh Zayed"
                        },
                        new
                        {
                            Id = 301,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Smouha"
                        },
                        new
                        {
                            Id = 302,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 303,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Stanley"
                        },
                        new
                        {
                            Id = 304,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Sidi Gaber"
                        },
                        new
                        {
                            Id = 401,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Mansoura"
                        },
                        new
                        {
                            Id = 402,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Mit Ghamr"
                        },
                        new
                        {
                            Id = 403,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Talkha"
                        },
                        new
                        {
                            Id = 501,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Zagazig"
                        },
                        new
                        {
                            Id = 502,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Belbeis"
                        },
                        new
                        {
                            Id = 503,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "10th of Ramadan"
                        },
                        new
                        {
                            Id = 601,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Banha"
                        },
                        new
                        {
                            Id = 602,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Shubra El Kheima"
                        },
                        new
                        {
                            Id = 603,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Qalyub"
                        },
                        new
                        {
                            Id = 701,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Port Fouad"
                        },
                        new
                        {
                            Id = 702,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "El Manakh"
                        },
                        new
                        {
                            Id = 801,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Aswan"
                        },
                        new
                        {
                            Id = 802,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Kom Ombo"
                        },
                        new
                        {
                            Id = 803,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Edfu"
                        });
                });

            modelBuilder.Entity("Threes.Registration.Domain.Lookups.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Governorates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Giza"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Dakahlia"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Sharqia"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Qalyubia"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Port Said"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Aswan"
                        });
                });

            modelBuilder.Entity("Threes.Registration.Domain.Registrations.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BuildingNumber");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FlatNumber");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Street");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Threes.Registration.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BirthDate");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MiddleName");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("Threes.Registration.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Threes.Registration.Domain.Lookups.City", b =>
                {
                    b.HasOne("Threes.Registration.Domain.Lookups.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Threes.Registration.Domain.Registrations.Address", b =>
                {
                    b.HasOne("Threes.Registration.Domain.Lookups.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Threes.Registration.Domain.Lookups.Governorate", null)
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Threes.Registration.Domain.Registrations.Registration", null)
                        .WithMany("Addresses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Threes.Registration.Domain.Registrations.Registration", b =>
                {
                    b.OwnsOne("Threes.Registration.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("EmailNormalized");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("RegistrationId");

                            b1.HasIndex("Normalized")
                                .IsUnique()
                                .HasDatabaseName("UX_Registrations_EmailNormalized");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("Threes.Registration.Domain.ValueObjects.MobileNumber", "Mobile", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("MobileNumber");

                            b1.HasKey("RegistrationId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UX_Registrations_MobileNumber");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Mobile")
                        .IsRequired();
                });

            modelBuilder.Entity("Threes.Registration.Domain.Lookups.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Threes.Registration.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
